version: "3.3"

services:
  mongodb:
    image: mongo
    container_name: db
    restart: always
    env_file: .env
    environment:
      # - MONGO_INITDB_DATABASE=$MONGO_DB_NAME
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
    command: [--auth]
    networks:
      - infrastructure
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      # - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - dbdata:/data/db

volumes:
  dbdata:

networks:
  infrastructure:
